CREATE DATABASE CAKE_MANAGEMENT;
USE CAKE_MANAGEMENT;

CREATE TABLE DONVITINH(
MaDVT INT AUTO_INCREMENT PRIMARY KEY,
Ten VARCHAR(255) NOT NULL
);

CREATE TABLE HANGSANXUAT(
MaHang INT AUTO_INCREMENT PRIMARY KEY,
TenHang VARCHAR(255) NOT NULL,
DiaChi VARCHAR(255)
);

CREATE TABLE NGUYENLIEU(
MaNL INT AUTO_INCREMENT PRIMARY KEY,
Ten VARCHAR(255) NOT NULL,
SoLuong INT,
DonGia DECIMAL(15,2),
MaDVT INT,
FOREIGN KEY (MaDVT) REFERENCES DONVITINH(MaDVT)
);

CREATE TABLE LOAIBANH(
MaLoai INT AUTO_INCREMENT PRIMARY KEY,
TenLoai VARCHAR(255) NOT NULL
);

CREATE TABLE CHUCVU(
MaChucVu INT AUTO_INCREMENT PRIMARY KEY,
TenChucVu VARCHAR(255)
);

CREATE TABLE NHANVIEN(
MaNV INT AUTO_INCREMENT PRIMARY KEY,
Ho VARCHAR(100) NOT NULL,
Ten VARCHAR(100) NOT NULL,
NgaySinh DATE,
LuongCoBan DECIMAL(15,2),
ChucVu INT,
FOREIGN KEY (ChucVu) REFERENCES CHUCVU(MaChucVu)
);

CREATE TABLE NHACUNGCAP(
MaNCC INT AUTO_INCREMENT PRIMARY KEY,
TenNCC VARCHAR(255) NOT NULL,
MaSoThue VARCHAR(255) NOT NULL
);

CREATE TABLE KHACHHANG(
MaKH INT AUTO_INCREMENT PRIMARY KEY,
Ho VARCHAR(255) NOT NULL,
Ten VARCHAR(255) NOT NULL,
DiaChi VARCHAR(255),
SDT VARCHAR(15)
);

CREATE TABLE HOADON(
MaHD INT AUTO_INCREMENT PRIMARY KEY,
NgayLapHD DATETIME DEFAULT NOW() NOT NULL,
MaNV INT,
MaKH INT,
ThanhTien DECIMAL(15,2),
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);

CREATE TABLE CHUONGTRINHKHUYENMAI(
MaKM INT AUTO_INCREMENT PRIMARY KEY,
TenCTKM VARCHAR(255),
NgayBatDau DATETIME DEFAULT NOW(),
NgayKetThuc DATETIME DEFAULT NOW(),
GhiChu VARCHAR(255)
);

CREATE TABLE PHIEUNHAPHANG(
MaPhieuNhap INT AUTO_INCREMENT PRIMARY KEY,
Ngay DATETIME DEFAULT NOW(),
MaNV INT,
MaNCC INT,
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);

CREATE TABLE BANH(
MaBanh INT AUTO_INCREMENT PRIMARY KEY,
TenBanh VARCHAR(255) NOT NULL,
SoLuong INT CHECK (SoLuong >= 0),
MaDVT INT,
MaLoai INT,
MaHang INT,
FOREIGN KEY (MaDVT) REFERENCES DONVITINH(MaDVT),
FOREIGN KEY (MaLoai) REFERENCES LOAIBANH(MaLoai),
FOREIGN KEY (MaHang) REFERENCES HANGSANXUAT(MaHang)
);

CREATE TABLE CT_PHIEUNHAPHANG(
MaPhieuNhap INT,
MaBanh INT,
MaNVL INT,
SoLuong INT NOT NULL CHECK (SoLuong >= 0),
DonGia DECIMAL(15,2) NOT NULL CHECK (DonGia >= 0),
ThanhTien DECIMAL(15,2) GENERATED ALWAYS AS (SoLuong * DonGia) STORED,
TinhTrang VARCHAR(255),
FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEUNHAPHANG(MaPhieuNhap),
FOREIGN KEY (MaBanh) REFERENCES BANH(MaBanh),
FOREIGN KEY (MaNVL) REFERENCES NGUYENLIEU(MaNL)
);

CREATE TABLE CHITIETHOADON(
MaHD INT,
MaBanh INT,
SoLuong INT NOT NULL CHECK (SoLuong >= 0),
DonGia DECIMAL(15,2) NOT NULL CHECK (DonGia >= 0),
ThanhTien DECIMAL(15,2) GENERATED ALWAYS AS (SoLuong * DonGia) STORED,
Diem INT,
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
FOREIGN KEY (MaBanh) REFERENCES BANH(MaBanh)
);

CREATE TABLE CT_CHUONGTRINHKHUYENMAI(
MaKM INT,
MaBanh INT,
PhamTramGiam INT CHECK (PhamTramGiam > 0 AND PhamTramGiam <= 100),
FOREIGN KEY (MaKM) REFERENCES CHUONGTRINHKHUYENMAI(MaKM),
FOREIGN KEY (MaBanh) REFERENCES BANH(MaBanh)
);

CREATE TABLE CONGTHUC(
MaBanh INT,
MaDVT INT,
CachLam VARCHAR(255),
FOREIGN KEY (MaBanh) REFERENCES BANH(MaBanh),
FOREIGN KEY (MaDVT) REFERENCES DONVITINH(MaDVT)
);

CREATE TABLE TICHDIEM(
MaKH INT,
TICHDIEM INT NOT NULL,
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);