CREATE DATABASE CAKE_MANAGEMENT;
USE CAKE_MANAGEMENT;

-- KHỞI TẠO DB


CREATE TABLE DONVITINH(
MaDVT INT IDENTITY(1,1) PRIMARY KEY,
Ten NVARCHAR(255) NOT NULL  )
GO

CREATE TABLE HANGSANXUAT(
MaHang INT IDENTITY(1,1) PRIMARY KEY,
TenHang NVARCHAR(255) NOT NULL,
DiaChi NVARCHAR(255) )
GO

CREATE TABLE NGUYENLIEU(
MaNL INT IDENTITY(1,1) PRIMARY KEY,
Ten NVARCHAR(255) NOT NULL,
SoLuong INT , 
DonGia FLOAT,
MaDVT INT ,
CONSTRAINT FK_NL_DVT FOREIGN KEY (MaDVT) REFERENCES DONVITINH(MaDVT))
GO

CREATE TABLE LOAIBANH(
MaLoai INT IDENTITY(1,1) PRIMARY KEY,
TenLoai NVARCHAR(255) NOT NULL )
GO

CREATE TABLE NHANVIEN(
MaNV INT IDENTITY(1,1) PRIMARY KEY,
Ho NVARCHAR(100) NOT NULL, 
Ten NVARCHAR(100) NOT NULL,
NgaySinh DATE ,
LuongCoBan Money ,
ChucVu INT )
GO

CREATE TABLE CHUCVU(
MaChucVu INT IDENTITY(1,1) PRIMARY KEY,
TenChucVu NVARCHAR(255) )
GO

CREATE TABLE NHACUNGCAP(
MaNCC INT IDENTITY(1,1) PRIMARY KEY,
TenNCC NVARCHAR(255) NOT NULL,
MaSoThue VARCHAR(255) NOT NULL)
GO

CREATE TABLE HOADON(
MaHD INT IDENTITY(1,1) PRIMARY KEY,
NgayLapHD DATETIME DEFAULT GETDATE() NOT NULL,
MaNV INT ,
MaKH INT ,
ThanhTien  MONEY)
GO


CREATE TABLE CHUONGTRINHKHUYENMAI(
MaKM INT IDENTITY(1,1) PRIMARY KEY,
TenCTKM	NVARCHAR(255),
NgayBatDau DATETIME DEFAULT GETDATE() NOT NULL ,
NgayKetThuc DATETIME DEFAULT GETDATE() NOT NULL,
GhiChu NVARCHAR(255)
)
GO



CREATE TABLE PHIEUNHAPHANG(
MaPhieuNhap INT IDENTITY(1,1) PRIMARY KEY,
Ngay DATETIME DEFAULT GETDATE() NOT NULL ,
MaNV INT , 
MaNCC INT ,
CONSTRAINT FK_PNH_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
CONSTRAINT FK_PNH_NCC FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
)
GO

CREATE TABLE BANH(
MaBanh INT IDENTITY(1,1) PRIMARY KEY, 
TenBanh NVARCHAR(255) NOT NULL ,
SoLuong INT CHECK(SoLuong >=0), 
MaDVT INT ,
MaLoai INT ,
MaHang INT ,
CONSTRAINT FK_BANH_DVT FOREIGN KEY (MaDVT) REFERENCES DONVITINH(MaDVT),
CONSTRAINT FK_BANH_LOAI FOREIGN KEY (MaLoai) REFERENCES LOAIBANH(MaLoai),
CONSTRAINT FK_BANH_HANGSX FOREIGN KEY (MaHang) REFERENCES HANGSANXUAT(MaHang)
)
GO 

CREATE TABLE CT_PHIEUNHAPHANG(
MaPhieuNhap INT ,
MaBanh INT ,
MaNVL INT , 
SoLuong INT NOT NULL CHECK(SoLuong >= 0), 
DonGia MONEY NOT NULL CHECK(DonGia >=0) ,
ThanhTien AS (SoLuong * DonGia), 
TinhTrang NVARCHAR(255),
CONSTRAINT FK_CTPNH_PNH FOREIGN KEY (MaPhieuNhap ) REFERENCES PHIEUNHAPHANG(MaPhieuNhap),
CONSTRAINT FK_CTPNH_BANH FOREIGN KEY (MaBanh) REFERENCES BANH(MaBanh),
CONSTRAINT FK_CTPNH_NVL FOREIGN KEY (MaNVL) REFERENCES NGUYENLIEU(MaNL)
)
GO

CREATE TABLE KHACHHANG(
MaKH INT IDENTITY(1,1) PRIMARY KEY,
Ho NVARCHAR(255) NOT NULL,
Ten NVARCHAR(255) NOT NULL ,
DiaChi NVARCHAR(255) ,
SDT INT )
GO


CREATE TABLE CHITIETHOADON(
MaHD INT , 
MaBanh INT ,
SoLuong INT NOT NULL CHECK(SoLuong >= 0),
DonGia MONEY NOT NULL CHECK(DonGia >= 0) ,
ThanhTien AS(SoLuong * DonGia),
Diem INT,
CONSTRAINT FK_CTHD_HD FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
CONSTRAINT FK_CTHD_BANH FOREIGN KEY (MaHD) REFERENCES BANH(MaBanh)
) 
GO 


CREATE TABLE CT_CHUONGTRINHKHUYENMAI(
MaKM INT IDENTITY(1,1) PRIMARY KEY,
MaBanh INT ,
PhamTramGiam INT NOT NULL CHECK(PhamTramGiam >0 AND PhamTramGiam <= 100),
CONSTRAINT FK_CTCTKM_BANH FOREIGN KEY (MaBanh) REFERENCES BANH(MaBanh),
CONSTRAINT FK_CTCTKM_CTKM FOREIGN KEY (MaKM) REFERENCES CHUONGTRINHKHUYENMAI(MaKM)
)
GO


CREATE TABLE CONGTHUC(
MaBanh INT NOT NULL ,
MaDVT INT ,
CachLam NVARCHAR(255),
CONSTRAINT FK_CT_BANH FOREIGN KEY (MaBanh) REFERENCES BANH(MaBanh),
CONSTRAINT FK_CT_DVT FOREIGN KEY (MaDVT) REFERENCES DONVITINH(MaDVT)
)
GO

CREATE TABLE TICHDIEM(
MaKH INT ,
TICHDIEM INT NOT NULL)
GO
--INDEX TỐI ƯU 

--TRIGGER 
--- TÍNH TỔNG TIỀN HÓA ĐƠN 
--PROCEDURE 